// swift-tools-version: 5.9
// AUTO-GENERATED by build.sh for RxSwift 6.7.0. Do not edit by hand.
import PackageDescription

let package = Package(
    name: "RxSwiftDynamic",
    platforms: [.iOS("15.0")],
    products: [
        .library(name: "RxSwift", targets: ["RxSwift"]),
        .library(name: "RxRelay", targets: ["RxRelay"]),
        .library(name: "RxCocoa", targets: ["RxCocoa"]),
        .library(name: "RxTest", targets: ["RxTest"]),
        .library(name: "RxBlocking", targets: ["RxBlocking"]),
    ],
    targets: [
        .binaryTarget(name: "RxSwift", url: "https://github.com/alex-pan-invos/rxswift-dynamic-xcframework/releases/download/6.7.0/RxSwift.xcframework.zip", checksum: "c4678a4d997919e468f93f2898beab7cecdb4ec1db6995132f958a4acd9f9a1d"),
        .binaryTarget(name: "RxRelay", url: "https://github.com/alex-pan-invos/rxswift-dynamic-xcframework/releases/download/6.7.0/RxRelay.xcframework.zip", checksum: "fff2f2a4f16ef9174402784f704cfd2adb098875dff94358e28062a885a0f27e"),
        .binaryTarget(name: "RxCocoa", url: "https://github.com/alex-pan-invos/rxswift-dynamic-xcframework/releases/download/6.7.0/RxCocoa.xcframework.zip", checksum: "6d7d11b36859e53fef67ecf4556d170633beefbe650b51c065a85d9a3bdcd0b5"),
        .binaryTarget(name: "RxTest", url: "https://github.com/alex-pan-invos/rxswift-dynamic-xcframework/releases/download/6.7.0/RxTest.xcframework.zip", checksum: "dc29c4637c0f94e0ba400a06637ab62062dc255bd323aff84730fa54bb55b67b"),
        .binaryTarget(name: "RxBlocking", url: "https://github.com/alex-pan-invos/rxswift-dynamic-xcframework/releases/download/6.7.0/RxBlocking.xcframework.zip", checksum: "41c7f4a7ee41b7723a0f5af0a84e8d11f0b348fd70a5119e21087551ca693389"),
    ]
)
